### ISSUE TITLE
Alternative Kelps Are Unobtainable

### ISSUE THREAD

**Issue by puncrafter** [MrAwesomeRocks/the-latest-summer-fun#10]
**Is your feature request related to a problem? Please describe. Link an issue if needed.**
There is no way to get the alternative kelps, which may be wanted for building purposes.

**Describe the solution you'd like**
Maybe some way to turn vanilla kelp into one of these other kelps? The kelps certainly don't want to generate on their own.

**Describe alternatives you've considered**
I haven't really considered anything else, because the only other thing I can think of is adding it to the wandering trader, and I don't know if that's even possible.

**Additional context**
Nope.

---

Who would you like to work on this issue?

- [ ] Yourself (i.e. you send in a PR)
- [x] Anyone

**Comment by MrAwesomeRocks** [comment]
Fixed (probably) in b1a1c27.
