### ISSUE TITLE
The Coffee, Tea, and Beer Brewing Recipes Aren't Working

### ISSUE THREAD

**Issue by puncrafter** [MrAwesomeRocks/the-latest-summer-fun#15]
**Describe the bug**

The recipes don't appear in JEI. I haven't tried brewing them myself, but I assume that they don't work since they aren't in JEI

**To Reproduce**

Look up the recipe, you will see that they do not, in fact, appear.

**Expected behavior**

They should appear

**Screenshots/Crash Log**

Nope

**Where is this bug happening? Check all that apply.**

- [ ] Singleplayer
- [x] Multiplayer
- [ ] Game load
- [ ] Other: **FILL HERE**

**Additional context**

There is nothing else

---

Who would you like to work on this issue?

- [ ] Yourself (i.e. you send in a PR)
- [x] Anyone

**Comment by MrAwesomeRocks** [comment]
Just needed a `/reload`.
