### ISSUE TITLE
Compressed lapis

### ISSUE THREAD

**Issue by AlemSnyder** [MrAwesomeRocks/the-latest-summer-fun#9]
EE compressed lapis does not work in create recipes.

In the create create crafting mechenism, if one puts EE compressed lapis insted of create compressed lapis, the recipe will not craft the items will fall to the ground.

**Comment by MrAwesomeRocks** [comment]
Which block does this not work in?

**Comment by MrAwesomeRocks** [comment]
Fixed in 9413a0e482d62156b8fe4f36d3d1da24c96d9524.

**Comment by MrAwesomeRocks** [comment]
https://github.com/Creators-of-Create/Create/wiki/0.3.2
